name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: The problem you are trying to solve
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Your idea, if you have one
